### ISSUE TITLE
Show licenses when building the wheelhouse

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pyansys#47]
As discussed in the PyAnsys API meeting, we should check that the dependencies included in the PyAnsys projects do not include any copyleft or similar products. Those must be identified and removed as soon as possible.

@PProfizi mentioned that it is possible to have a bot causing the workflow to fail if any of them are present. We should consider implementing it.

**Comment by PProfizi** [comment]
Was thinking about [this](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement) if I remember correctly.
